version: '3.9'

services:
  readingisgood:
    image: readingisgood
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=mhu
      - DB_PASSWORD=41417

  postgres:
    image: "postgres"
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: mhu
      POSTGRES_PASSWORD: 41417
    volumes:
      - readingisgood-volume:/var/lib/postgres/data


volumes:
  readingisgood-volume:
